site_name: PokerSplitter Documentation
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API Reference:
    - splitter: splitter.md
    - patterns: patterns.md
    - main: main.md
    - directories: directories.md
      